[DOC] Add a raptor search tutorial
seqan/raptor pull request #197
Opened 2022-11-16 11:52 UTC by Irallia

2022-12-06 15:06 UTC, Irallia commented on doc/tutorial/03_search/index.md
> +From the first assignment in the last tutorial we want to use the more usefull `raptor2.index` and do two searches on it.
Use minimiser.index

2022-12-06 15:07 UTC, Irallia commented on doc/tutorial/03_search/index.md
> +
add a hibf assignment with using hibf2.index?

2022-12-12 14:34 UTC, eseiler requested changes

2022-12-12 14:34 UTC, eseiler commented on doc/tutorial/04_search/index.md
> +You will learn how to searche a Raptor index using one or more sequences queries.
```suggestion
You will learn how to search a Raptor index using one or more sequences queries.
```

2022-12-12 14:34 UTC, eseiler commented on doc/tutorial/04_search/index.md
> +Now we want to have a look at Raptors second method: `raptor search`.
```suggestion
Now we want to have a look at Raptor's second method: `raptor search`.
```

2022-12-12 14:34 UTC, eseiler commented on doc/tutorial/04_search/index.md
> +But before we delve deeper into the various possibilities and parameters. We can start a first search with the indexes
```suggestion
But before that, we delve deeper into the various possibilities and parameters. We can start a first search with the indexes
```

2022-12-12 14:34 UTC, eseiler commented on doc/tutorial/04_search/index.md
> +Lets search for the queries `CGCGTTCATT` amd `CGCGTCATT` with the first two indexes, with creating a `search.output` and
The query is shorter than k (19 for the first index, 4 for the second).
I don't check this (you usually search long sequences), but it needs to be >=k.

2022-12-12 14:34 UTC, eseiler commented on doc/tutorial/04_search/index.md
> +\todo wollen wir die Raptor überschrift im image abschneiden?
Done?

2022-12-12 14:34 UTC, eseiler commented on doc/tutorial/04_search/index.md
> +Warum hat query2 keinen match?
See other comment about `k`

2022-12-12 15:40 UTC, eseiler approved these changes

2022-12-12 15:40 UTC, merged